[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
[project]
requires-python = ">=3.6"
dependencies = [
  "biopython=1.81",
  "pandas",
  "numpy",
  "scipy",
  "matplotlib",
  "plotly"
]
